# Site settings
title: Harris Bienn
name: Harris Bienn
email: harris.bienn@gmail.com

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/harris-bienn-94a28785/
 - title: ResearchGate
   url: https://www.researchgate.net/profile/Harris_Bienn

#Any buzzword skills you want to include
skills:
 - Transdisciplinary Research
 - Digital Cartography
 - Geospatial Analysis 
 - Scientific Visualization
 - Narrative Development
 - Social Vulnerability Assessment 
 - Geostatistics
 - Data Management 
 - Data Standards Development

#Work experience is required
roles:
 - title: Geospatial Scientist, Research Associate, Research Intern
   start: 2014
   end: Ongoing
   employer: The Water Institute of the Gulf, Baton Rouge, Louisiana
   description: Role requirements - Geospatial analysis, research, and narrative building for scientific communication. Data visualization and cartographic development. Administration of web GIS platforms and quality control of geospatial products.
 - title: Process Technician
   start: 2012
   end: 2014
   employer: Jacobs Engineering, Exxon Refinery Alliance Group, Baton Rouge, Louisiana
   description: Role requirements - Intensive analytical research on major turnaround projects for Exxon. Upstream and downstream communication and ideation.
 - title: Infantry Section Leader, Weapons Platoon Sergeant
   start: 2008
   end: 2012
   employer: United State Marine Corps
   description: Role requirements - Management and control of stressful situations. Command of section (15+ Marines) and platoon (45+ Marines) during consecutive combat deployments to Afghanistan.

#Education is required
education:
 - level: Bachelor of Science in Engineering (B.S. Eng.)
   date: 2018
   subject: Environmental Engineering
   school: Louisiana State University
   thesis: Assessing the Impact of Urban Flooding on Vulnerable Populations in New Orleans using the Internet of Things
 - level: Honors Graduate
   date: 2011
   subject: Infantry Squad Leaders Course
   school: United States Marine Corps Leadership Academy
   curriculum focus: Leadership and poise in high pressure settings. Emphasis on dynamic problem solving.

#This section is optional (as is the image link below)
#coursera:
   #profileurl: https://www.coursera.org/xxx
   #courses:
    #- title: Functional Programming Principles in Scala
      #link: https://www.coursera.org/course/xxx
      #optionalimage: 
      #date: 
    #- title: Algorithms Design and Analysis, Part 1
      #link: https://www.coursera.org/specializations/xxx
      #optionalimage: 
      #date: 
      
#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
   #profileurl: https://speakerdeck.com/xxxx
   #talks:
    #- title: 
      #speakerdeckId: 
      #conference: 
    #- title: 
      #speakerdeckId: 
      #conference: 

#List of interesting Github repo/projects to include - optional
github:
 - github.com/waterinstitute/avian_data_ingestor

#Stackoverflow flair is optional
#stackoverflow:
   #profileurl:
   #flairimageurl:

intro: |
  Highly qualified leader with more than eight years of experience in scientific research fields. Disciplined problem solver with excellent communication and analytical skills.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
skillsresume: |
   <strong>Software</strong>: Extensive - Anaconda3, ArcGIS Desktop (ArcMap), ArcGIS Online, ArcGIS Pro, Maptionnaire, Microsoft Office Suite, QGIS. Proficient - Adobe Creative Suite, ArcGIS Enterprise, CyberDuck, GRASS, iD (MapBox), jamovi, Leaflet, MapInfo Pro, MATLAB, RStudio, SPSS, Visual Studio 
   <strong>Programming Languages</strong>: Extensive - Python, SQL.  
   <strong>Operating Systems</strong>: Extensive - macOS, Windows. Proficient - MATLAB, R
   <strong>Modeling</strong>: Extensive - ArcGIS Model Builder, HAZUS. Proficient - HEC-GeoHMS, HEC-RAS, SWMM
   <strong>Methodological</strong>: Cartographic development, geodata processing and visualization, hazard assessment, scientific graphic development, social vulnerability assessment, statistical analysis, transdisciplinary research, data management, data standards development
   <strong>Interpersonal</strong>: Autodidactic and detail-orientated team player. Dedicated worker willing to share and teach associates. Disciplined problem solver with limited need for supervision.
additionalinfo: |
   Avid outdoorsman, backpacker and fisherman. Multiple treks throughout the Lower Appalachians, the Sierra Nevadas, and Mojave National Preserve. 
   Experienced technical diver with more than 100 hours underwater. Capable of underwater surveying and conduct of search and rescue activities. 
   Volunteer for Habitat for Humanity, The Nature Conservancy, and the Greater Baton Rouge Food Bank. 

   
